FROM ubuntu:latest
# Оновлюємо стандартні пакети
RUN apt-get update && apt-get upgrade -y

# Встановлюємо пакети, необхідні для компіляції та виконання програм на C++
RUN apt-get install -y build-essential gcc gdb

# Встановлюємо пакети, необхідні для виконання програм на C++
RUN apt-get install -y libboost-all-dev

# Копіюємо виконуваний файл у контейнер
COPY my_app /app/

# Перевіряємо робочу директорію
WORKDIR /app

# Виконуємо виконуваний файл
CMD ["./my_app"]
